### ISSUE TITLE
Diagnostic: Line Too Long feature broken

### ISSUE THREAD

**Issue by spiroharvey** [gverduci/c64basicv2#1]
Hi, the recent addition of a diagnostic checking the line is over 80 characters is broken and is reporting lots of my lines have problems when they don't.

Disabling the feature in the settings still leaves the file marked as full of errors once the diagnostic has run over that file.

Take this line for example:

135 print "{right}{right}{right}{right}{right}{right}{right}{right}{right}{right}{right}{right}{right}{right}{right}{right}{right}{right}{right}{right}{right}{right}{right}{right}{right}{right}{right}{right}{yellow}";

This is only 42 characters long once the control characters are converted, and the diagnostic is incorrectly marking it as over 80 characters.

**Comment by gverduci** [comment]
Hi, thank you for this report. I fixed the problem. Now a control character only counts for one.
