### ISSUE TITLE
Windows (Path) support

### ISSUE THREAD

**Issue by leonpierre** [gverduci/c64basicv2#3]
I tried to configure this extension on windows but were not able to find out how to avoid the issue
with the relative path to the bin folder after executing the convert command:

c64basicv2: "\c:\Projects\C64Playground\Basic\Snake\bin" folder doesn't exist!

**petcat:** C:\Program Files\Vice\bin\petcat.exe
**x64sc:** C:\Program Files\Vice\bin\x64sc.exe
**Convert output path:** Basic\Snake\bin

**Comment by gverduci** [comment]
problem fixed in v0.6.7
